/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinalOpinionsRouteImport } from './routes/final-opinions'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupaApiSplatRouteImport } from './routes/supa-api.$'
import { Route as ApiPublicDiagnosticoCursosRouteImport } from './routes/api/public/diagnostico-cursos'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalOpinionsRoute = FinalOpinionsRouteImport.update({
  id: '/final-opinions',
  path: '/final-opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupaApiSplatRoute = SupaApiSplatRouteImport.update({
  id: '/supa-api/$',
  path: '/supa-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagnosticoCursosRoute =
  ApiPublicDiagnosticoCursosRouteImport.update({
    id: '/api/public/diagnostico-cursos',
    path: '/api/public/diagnostico-cursos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/final-opinions': typeof FinalOpinionsRoute
  '/login': typeof LoginRoute
  '/processes': typeof ProcessesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/supa-api/$': typeof SupaApiSplatRoute
  '/api/public/diagnostico-cursos': typeof ApiPublicDiagnosticoCursosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/final-opinions': typeof FinalOpinionsRoute
  '/login': typeof LoginRoute
  '/processes': typeof ProcessesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/supa-api/$': typeof SupaApiSplatRoute
  '/api/public/diagnostico-cursos': typeof ApiPublicDiagnosticoCursosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/final-opinions': typeof FinalOpinionsRoute
  '/login': typeof LoginRoute
  '/processes': typeof ProcessesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/supa-api/$': typeof SupaApiSplatRoute
  '/api/public/diagnostico-cursos': typeof ApiPublicDiagnosticoCursosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/diagnostico'
    | '/final-opinions'
    | '/login'
    | '/processes'
    | '/reports'
    | '/reset-password'
    | '/users'
    | '/supa-api/$'
    | '/api/public/diagnostico-cursos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/diagnostico'
    | '/final-opinions'
    | '/login'
    | '/processes'
    | '/reports'
    | '/reset-password'
    | '/users'
    | '/supa-api/$'
    | '/api/public/diagnostico-cursos'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/diagnostico'
    | '/final-opinions'
    | '/login'
    | '/processes'
    | '/reports'
    | '/reset-password'
    | '/users'
    | '/supa-api/$'
    | '/api/public/diagnostico-cursos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FinalOpinionsRoute: typeof FinalOpinionsRoute
  LoginRoute: typeof LoginRoute
  ProcessesRoute: typeof ProcessesRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsersRoute: typeof UsersRoute
  SupaApiSplatRoute: typeof SupaApiSplatRoute
  ApiPublicDiagnosticoCursosRoute: typeof ApiPublicDiagnosticoCursosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-opinions': {
      id: '/final-opinions'
      path: '/final-opinions'
      fullPath: '/final-opinions'
      preLoaderRoute: typeof FinalOpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supa-api/$': {
      id: '/supa-api/$'
      path: '/supa-api/$'
      fullPath: '/supa-api/$'
      preLoaderRoute: typeof SupaApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostico-cursos': {
      id: '/api/public/diagnostico-cursos'
      path: '/api/public/diagnostico-cursos'
      fullPath: '/api/public/diagnostico-cursos'
      preLoaderRoute: typeof ApiPublicDiagnosticoCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FinalOpinionsRoute: FinalOpinionsRoute,
  LoginRoute: LoginRoute,
  ProcessesRoute: ProcessesRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsersRoute: UsersRoute,
  SupaApiSplatRoute: SupaApiSplatRoute,
  ApiPublicDiagnosticoCursosRoute: ApiPublicDiagnosticoCursosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
